// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package {{.TplPackageName}}

import (
	"{{.TplImportPrefix}}/internal"
)

// {{.TplTableNameCamelLowerCase}}Dao is the data access object for the table {{.TplTableName}}.
// You can define custom methods on it to extend its functionality as needed.
type {{.TplTableNameCamelLowerCase}}Dao struct {
	*internal.{{.TplTableNameCamelCase}}Dao
}

var (
    // {{.TplTableNameCamelCase}} is a globally accessible object for table {{.TplTableName}} operations.
	{{.TplTableNameCamelCase}} = {{.TplTableNameCamelLowerCase}}Dao{internal.New{{.TplTableNameCamelCase}}Dao()}
)

// Add your custom methods and functionality below.
